version: '3.9'

services:
  backend:
    build: ./backend
    container_name: odrl-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - odrl-demo-net

  frontend:
    build: ./frontend
    container_name: odrl-frontend
    env_file:
      - ./frontend/.env
    environment:
      REACT_APP_API_URL: http://backend:8000  # Docker internal hostname
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - odrl-demo-net

networks:
  odrl-demo-net:
    driver: bridge
